Demo
SnowScriptWinterOfCode/UI-UX-Case-Studies pull request #14
Opened 2024-01-01 12:34 UTC by prathna17

2024-01-04 15:58 UTC, PriyaDeveloper630 requested changes
Kindly add your readme in a folder which is named after your case study and also write a bit about the problem statement you took up as well as inspiration behind it.
Do consider adding more screens in your application that could help understand the project in a better manner.

2024-01-06 13:49 UTC, Nitya-Pasrija requested changes
Please rename the review file with a ".md" extension

2024-01-06 14:16 UTC, prathna17 commented
I have done the changes. Kindly review it.

2024-01-06 16:56 UTC, Nitya-Pasrija approved these changes

2024-01-06 16:57 UTC, merged