added UI UX case study for doubt solving website
SnowScriptWinterOfCode/UI-UX-Case-Studies pull request #7
Opened 2023-12-29 11:52 UTC by ANSHIKA-26

2023-12-29 11:52 UTC, Nitya-Pasrija reviewed
Perfection! Advancing through the open source world!🎊🎊 :) Please be patient while our maintainers and reviewers check the code.

2023-12-29 18:50 UTC, Nitya-Pasrija requested changes
The background in the design and the rating stars is not a clear UI, would recommend changing it

2023-12-31 15:33 UTC, Nitya-Pasrija commented
@ANSHIKA-26 
Any updates?

2023-12-31 16:47 UTC, ANSHIKA-26 commented on Doubtstrom/Doubtstrom.md
> +Figma link for ui ux:https://www.figma.com/file/9Di7Or75R1Idb9IU6NjgYA/Doubtstrom?type=design&node-id=18%3A3&mode=design&t=GYGJIwhBw5G7IHnf-1
New figma link : https://www.figma.com/file/9Di7Or75R1Idb9IU6NjgYA/Doubtstrom?type=design&node-id=18%3A3&mode=design&t=sBHDCwsLBNtL9DKN-1

2024-01-10 17:48 UTC, PriyaDeveloper630 commented on Doubtstrom/Doubtstrom.md
> +Figma link for ui ux:https://www.figma.com/file/9Di7Or75R1Idb9IU6NjgYA/Doubtstrom?type=design&node-id=18%3A3&mode=design&t=GYGJIwhBw5G7IHnf-1
> New figma link : https://www.figma.com/file/9Di7Or75R1Idb9IU6NjgYA/Doubtstrom?type=design&node-id=18%3A3&mode=design&t=sBHDCwsLBNtL9DKN-1

Would recommend adding more pages and functionalities to the design.

2024-01-17 17:31 UTC, Nitya-Pasrija approved these changes

2024-01-17 17:31 UTC, merged